# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 08:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsor', '0002_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=140)),
                ('postal_code', models.CharField(max_length=140)),
                ('country', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=140)),
                ('website', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=140)),
                ('about', models.CharField(max_length=140)),
                ('status', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1)),
                ('profile_picture', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/sponsor_photos'), upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
