# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('short', models.CharField(max_length=75)),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('note2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_sign_up', models.DateField(default=django.utils.timezone.now)),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('note2', models.CharField(blank=True, max_length=100)),
                ('note3', models.TextField(blank=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Currency')),
            ],
        ),
    ]
